// <auto-generated />
using System;
using DesafioConcrete.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioConcrete.Migrations
{
    [DbContext(typeof(LoginContext))]
    [Migration("20200319052452_inicializacao")]
    partial class inicializacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioConcrete.Model.CreateLogin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Token");

                    b.Property<int?>("contatoid");

                    b.Property<DateTime>("data_atualizacao");

                    b.Property<DateTime>("data_criacao");

                    b.Property<string>("email");

                    b.Property<string>("nome");

                    b.Property<string>("senha");

                    b.Property<DateTime>("ultimo_login");

                    b.HasKey("id");

                    b.HasIndex("contatoid");

                    b.ToTable("CreateLogins");
                });

            modelBuilder.Entity("DesafioConcrete.Model.Telefone", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("ddd");

                    b.Property<string>("numero");

                    b.HasKey("id");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("DesafioConcrete.Model.CreateLogin", b =>
                {
                    b.HasOne("DesafioConcrete.Model.Telefone", "contato")
                        .WithMany()
                        .HasForeignKey("contatoid");
                });
#pragma warning restore 612, 618
        }
    }
}
